### ISSUE TITLE
Does not work with column-fill / feature request

### ISSUE THREAD

**Issue by czarcar** [johnny/jquery-sortable#271]
I have a very long list that needs to be sorted manually.  If I apply the CSS columns, column-fill properties (to display the list as multiple columns), in my case 6 columns, the list does not sort properly.  Without CSS applied works properly.

```css
ratecenters {
        -webkit-columns: 6 200px;
        -moz-columns: 6 200px;
        columns: 6 200px;
        -moz-column-fill: auto;
        column-fill: balance;
    }
```
```html
<ratecenters>
                <ul id="sortable" class="list-group">
                    <li class="list-group-item" id="ratecenter_order_1">location 1</li>
                    <li class="list-group-item" id="ratecenter_order_2">location 2</li>
                    <li class="list-group-item" id="ratecenter_order_3">location 3</li>
                     ...........
                </ul>
</ratecenters>
```
